/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  devServerPort: 8002,
  serverBuildTarget: "netlify",
  // serverBuildTarget: "netlify-edge",
  server: "./server-entry.js",
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    "@milkdown/core",
    "@milkdown/react",
    "@milkdown/ctx",
    "@milkdown/exception",
    "@milkdown/transformer",
    "@milkdown/design-system",
    // "nanoid",
    // "remark",
    // "unified",
    // "remark-parse",
    // "remark-stringify",
    // "bail",
    // "mdast-util-to-markdown",
    // "trough",
    // "vfile",
    // "longest-streak",
    // "micromark-util-decode-string",
    // "vfile-message",
    // "zwitch",
    // "unist-util-visit",
    // "micromark-util-decode-numeric-character-reference",
    // "decode-named-character-reference",
    // "unist-util-visit-parents",
    // "unist-util-stringify-position",
    // "mdast-util-to-string",
    // "mdast-util-from-markdown",
    // "micromark-util-normalize-identifier",
    // "character-entities",
    // "unist-util-is",
    // "micromark"
  ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: ".netlify/functions-internal/server.js",
  // publicPath: "/build/",
};
