/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type ConstantPostType = "TEXT" | "BAIDU_DOWNLOAD" | "TEXT_WITH_IMAGE" | "ENUM_POST_IMAGE" | "ENUM_POST_AUDIO" | "ENUM_POST_VIDEO" | "ARTICLE" | "POST_ASK" | "TEXT_AUDIO" | "TEXT_VIDEO" | "ENUM_POST_LINK" | "FILE" | "UPHAND" ;
