/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HorseCardReturn } from './HorseCardReturn';
import { HorseSeriesWithMeta } from './HorseSeriesWithMeta';
import { KunProfile } from './KunProfile';
import { NoSqlPagingListDataKunAppraiseRet } from './NoSqlPagingListDataKunAppraiseRet';
import { HttpFile } from '../http/http';

export class HorseSeriesFull {
    'series': HorseSeriesWithMeta;
    'authorProfile': KunProfile;
    'cards'?: Array<HorseCardReturn>;
    'comments': NoSqlPagingListDataKunAppraiseRet;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "series",
            "baseName": "series",
            "type": "HorseSeriesWithMeta",
            "format": ""
        },
        {
            "name": "authorProfile",
            "baseName": "authorProfile",
            "type": "KunProfile",
            "format": ""
        },
        {
            "name": "cards",
            "baseName": "cards",
            "type": "Array<HorseCardReturn>",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "NoSqlPagingListDataKunAppraiseRet",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HorseSeriesFull.attributeTypeMap;
    }

    public constructor() {
    }
}

