/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantPostType } from './ConstantPostType';
import { HttpFile } from '../http/http';

export class HorseCardReturn {
    'cardId': string;
    'seriesId': string;
    'authorId': string;
    'seriesVersion': number;
    'title': string;
    'postType': ConstantPostType;
    'content': string;
    'richHtml'?: string;
    'delta'?: string;
    'audioName'?: string;
    'videoName'?: string;
    'imageNames'?: Array<string>;
    'isDelete': boolean;
    'likeCount': number;
    'commentCount': number;
    'noteCount': number;
    'createAt': number;
    'updateAt': number;
    'cardOrder': number;
    'read'?: boolean;
    'textAudio'?: string;
    'tags'?: Array<string>;
    'isRead': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardId",
            "baseName": "cardId",
            "type": "string",
            "format": ""
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "seriesVersion",
            "baseName": "seriesVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "postType",
            "baseName": "postType",
            "type": "ConstantPostType",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "richHtml",
            "baseName": "richHtml",
            "type": "string",
            "format": ""
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "string",
            "format": ""
        },
        {
            "name": "audioName",
            "baseName": "audioName",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoName",
            "baseName": "videoName",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageNames",
            "baseName": "imageNames",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isDelete",
            "baseName": "isDelete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "likeCount",
            "baseName": "likeCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "commentCount",
            "baseName": "commentCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "noteCount",
            "baseName": "noteCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "updateAt",
            "baseName": "updateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "cardOrder",
            "baseName": "cardOrder",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "read",
            "baseName": "read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "textAudio",
            "baseName": "textAudio",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isRead",
            "baseName": "isRead",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HorseCardReturn.attributeTypeMap;
    }

    public constructor() {
    }
}

