/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class HorseSecondCategory {
    'id': number;
    'name': string;
    'seq': number;
    'catId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number",
            "format": ""
        },
        {
            "name": "catId",
            "baseName": "cat_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return HorseSecondCategory.attributeTypeMap;
    }

    public constructor() {
    }
}

