/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantChargeType } from './ConstantChargeType';
import { ConstantSeriesType } from './ConstantSeriesType';
import { HttpFile } from '../http/http';

export class HorseSeriesWithMeta {
    'cardCount': number;
    'id': string;
    'title': string;
    'authorId': string;
    'seriesType': ConstantSeriesType;
    'isAuthor': boolean;
    'latestVersion': number;
    'releaseVersion': number;
    'description'?: string;
    'learnPerDay'?: number;
    'tags'?: Array<string>;
    'categoryId'?: number;
    'subCategoryId'?: number;
    'price'?: number;
    'coverImageName'?: string;
    'chargeType': ConstantChargeType;
    'learningByAuthor': boolean;
    'releaseUpdateAt'?: number;
    'releaseCreateAt'?: number;
    'createAt': number;
    'categoryName'?: string;
    'subscriptionCount': number;
    'descriptionDelta'?: string;
    'discountPrice'?: number;
    'appriseScore'?: number;
    'appriseNum'?: number;
    'aim'?: string;
    'manager'?: string;
    'managerName'?: string;
    'wechatImageName'?: string;
    'practiceCount'?: number;
    'groupId': string;
    'visible': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardCount",
            "baseName": "cardCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "seriesType",
            "baseName": "seriesType",
            "type": "ConstantSeriesType",
            "format": ""
        },
        {
            "name": "isAuthor",
            "baseName": "isAuthor",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "latestVersion",
            "baseName": "latestVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "releaseVersion",
            "baseName": "releaseVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "learnPerDay",
            "baseName": "learnPerDay",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subCategoryId",
            "baseName": "subCategoryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "coverImageName",
            "baseName": "coverImageName",
            "type": "string",
            "format": ""
        },
        {
            "name": "chargeType",
            "baseName": "chargeType",
            "type": "ConstantChargeType",
            "format": ""
        },
        {
            "name": "learningByAuthor",
            "baseName": "learningByAuthor",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "releaseUpdateAt",
            "baseName": "releaseUpdateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "releaseCreateAt",
            "baseName": "releaseCreateAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "categoryName",
            "baseName": "categoryName",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscriptionCount",
            "baseName": "subscriptionCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "descriptionDelta",
            "baseName": "descriptionDelta",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountPrice",
            "baseName": "discountPrice",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "appriseScore",
            "baseName": "appriseScore",
            "type": "number",
            "format": ""
        },
        {
            "name": "appriseNum",
            "baseName": "appriseNum",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "aim",
            "baseName": "aim",
            "type": "string",
            "format": ""
        },
        {
            "name": "manager",
            "baseName": "manager",
            "type": "string",
            "format": ""
        },
        {
            "name": "managerName",
            "baseName": "managerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "wechatImageName",
            "baseName": "wechatImageName",
            "type": "string",
            "format": ""
        },
        {
            "name": "practiceCount",
            "baseName": "practiceCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HorseSeriesWithMeta.attributeTypeMap;
    }

    public constructor() {
    }
}

