/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class KunAppraiseRet {
    'channelId': number;
    'feedId': string;
    'appraiseScore': number;
    'createAt': number;
    'commentUserName'?: string;
    'commentUserAvatar'?: string;
    'userId': string;
    'comment'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "feedId",
            "baseName": "feedId",
            "type": "string",
            "format": ""
        },
        {
            "name": "appraiseScore",
            "baseName": "appraiseScore",
            "type": "number",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "commentUserName",
            "baseName": "commentUserName",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentUserAvatar",
            "baseName": "commentUserAvatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunAppraiseRet.attributeTypeMap;
    }

    public constructor() {
    }
}

