/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class KunProfile {
    'channelId': number;
    'userId': string;
    'brandName'?: string;
    'brandDescription'?: string;
    'brandAvatarName'?: string;
    'provinceId'?: string;
    'provinceName'?: string;
    'cityId'?: string;
    'cityName'?: string;
    'wechatContact'?: string;
    'urlName'?: string;
    'bilibli'?: string;
    'bilibliVerified'?: boolean;
    'weibo'?: string;
    'weiboVerified'?: boolean;
    'douyin'?: string;
    'douyinVerified'?: boolean;
    'zhihu'?: string;
    'zhihuVerified'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "brandName",
            "baseName": "brandName",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandDescription",
            "baseName": "brandDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandAvatarName",
            "baseName": "brandAvatarName",
            "type": "string",
            "format": ""
        },
        {
            "name": "provinceId",
            "baseName": "provinceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "provinceName",
            "baseName": "provinceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "cityId",
            "baseName": "cityId",
            "type": "string",
            "format": ""
        },
        {
            "name": "cityName",
            "baseName": "cityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "wechatContact",
            "baseName": "wechatContact",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlName",
            "baseName": "urlName",
            "type": "string",
            "format": ""
        },
        {
            "name": "bilibli",
            "baseName": "bilibli",
            "type": "string",
            "format": ""
        },
        {
            "name": "bilibliVerified",
            "baseName": "bilibliVerified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weibo",
            "baseName": "weibo",
            "type": "string",
            "format": ""
        },
        {
            "name": "weiboVerified",
            "baseName": "weiboVerified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "douyin",
            "baseName": "douyin",
            "type": "string",
            "format": ""
        },
        {
            "name": "douyinVerified",
            "baseName": "douyinVerified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "zhihu",
            "baseName": "zhihu",
            "type": "string",
            "format": ""
        },
        {
            "name": "zhihuVerified",
            "baseName": "zhihuVerified",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunProfile.attributeTypeMap;
    }

    public constructor() {
    }
}

