/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class KunSymbol {
    'channelId': number;
    'symbol': string;
    'title': string;
    'coverImageUrl'?: string;
    'description'?: string;
    'backgroundImageUrl'?: string;
    'tags'?: Array<string>;
    'createAt': number;
    'isRobot'?: boolean;
    'createUserId'?: string;
    'createUserName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "coverImageUrl",
            "baseName": "coverImageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "backgroundImageUrl",
            "baseName": "backgroundImageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "isRobot",
            "baseName": "isRobot",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createUserId",
            "baseName": "createUserId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createUserName",
            "baseName": "createUserName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KunSymbol.attributeTypeMap;
    }

    public constructor() {
    }
}

