/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoItem } from './VideoItem';
import { HttpFile } from '../http/http';

export class NextVideo {
    'push'?: VideoItem;
    'list'?: Array<VideoItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "push",
            "baseName": "push",
            "type": "VideoItem",
            "format": ""
        },
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<VideoItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NextVideo.attributeTypeMap;
    }

    public constructor() {
    }
}

