/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';
import type { ConstantMSG1 } from './ConstantMSG1';
import type { HorseSeriesReturn } from './HorseSeriesReturn';

export class NoSqlPagingListHorseSeriesReturn {
    'code': ConstantMSG1;
    'msg': string;
    'records'?: Array<HorseSeriesReturn>;
    'pageState'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ConstantMSG1",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "records",
            "baseName": "records",
            "type": "Array<HorseSeriesReturn>",
            "format": ""
        },
        {
            "name": "pageState",
            "baseName": "pageState",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NoSqlPagingListHorseSeriesReturn.attributeTypeMap;
    }

    public constructor() {
    }
}

