/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantPostType } from './ConstantPostType';
import { HttpFile } from '../http/http';

export class ReqUpdateHorseCard {
    'cardId': string;
    'seriesId': string;
    'title': string;
    'richHtml'?: string;
    'delta'?: string;
    'audioName'?: string;
    'videoName'?: string;
    'imageNames'?: Array<string>;
    'content': string;
    'postType': ConstantPostType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardId",
            "baseName": "cardId",
            "type": "string",
            "format": ""
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "richHtml",
            "baseName": "richHtml",
            "type": "string",
            "format": ""
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "string",
            "format": ""
        },
        {
            "name": "audioName",
            "baseName": "audioName",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoName",
            "baseName": "videoName",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageNames",
            "baseName": "imageNames",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "postType",
            "baseName": "postType",
            "type": "ConstantPostType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqUpdateHorseCard.attributeTypeMap;
    }

    public constructor() {
    }
}

