/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RespstockFinancialAnalysisIndicatorResponse {
    'pRi4qi1': string;
    'pTan1bo2mei3gu3shou1yi4yuan2': string;
    'pJia1quan2mei3gu3shou1yi4yuan2': string;
    'pMei3gu3shou1yi4diao4zheng3hou4yuan2': string;
    'pKou4chu2fei1jing1chang2xing4sun3yi4hou4de5mei3gu3shou1yi4yuan2': string;
    'pMei3gu3jing4zi1chan3diao4zheng3qian2yuan2': string;
    'pMei3gu3jing4zi1chan3diao4zheng3hou4yuan2': string;
    'pMei3gu3jing1ying2xing4xian4jin1liu2yuan2': string;
    'pMei3gu3zi1ben3gong1ji1jin1yuan2': string;
    'pMei3gu3wei4fen1pei4li4run4yuan2': string;
    'pDiao4zheng3hou4de5mei3gu3jing4zi1chan3yuan2': string;
    'pZong3zi1chan3li4run4lu4': string;
    'pZhu3ying2ye4wu4li4run4lu4': string;
    'pZong3zi1chan3jing4li4run4lu4': string;
    'pCheng2ben3fei4yong4li4run4lu4': string;
    'pYing2ye4li4run4lu4': string;
    'pZhu3ying2ye4wu4cheng2ben3lu4': string;
    'pXiao1shou4jing4li4lu4': string;
    'pGu3ben3bao4chou2lu4': string;
    'pJing4zi1chan3bao4chou2lu4': string;
    'pZi1chan3bao4chou2lu4': string;
    'pXiao1shou4mao2li4lu4': string;
    'pSan1xiang4fei4yong4bi3zhong4': string;
    'pFei1zhu3ying2bi3zhong4': string;
    'pZhu3ying2li4run4bi3zhong4': string;
    'pGu3xi1fa1fang4lu4': string;
    'pTou2zi1shou1yi4lu4': string;
    'pZhu3ying2ye4wu4li4run4yuan2': string;
    'pJing4zi1chan3shou1yi4lu4': string;
    'pJia1quan2jing4zi1chan3shou1yi4lu4': string;
    'pKou4chu2fei1jing1chang2xing4sun3yi4hou4de5jing4li4run4yuan2': string;
    'pZhu3ying2ye4wu4shou1ru4zeng1zhang3lu4': string;
    'pJing4li4run4zeng1zhang3lu4': string;
    'pJing4zi1chan3zeng1zhang3lu4': string;
    'pZong3zi1chan3zeng1zhang3lu4': string;
    'pYing1shou1zhang4kuan3zhou1zhuan3lu4ci4': string;
    'pYing1shou1zhang4kuan3zhou1zhuan3tian1shu4tian1': string;
    'pCun2huo4zhou1zhuan3tian1shu4tian1': string;
    'pCun2huo4zhou1zhuan3lu4ci4': string;
    'pGu4ding4zi1chan3zhou1zhuan3lu4ci4': string;
    'pZong3zi1chan3zhou1zhuan3lu4ci4': string;
    'pZong3zi1chan3zhou1zhuan3tian1shu4tian1': string;
    'pLiu2dong4zi1chan3zhou1zhuan3lu4ci4': string;
    'pLiu2dong4zi1chan3zhou1zhuan3tian1shu4tian1': string;
    'pGu3dong1quan2yi4zhou1zhuan3lu4ci4': string;
    'pLiu2dong4bi3lu4': string;
    'pSu4dong4bi3lu4': string;
    'pXian4jin1bi3lu4': string;
    'pLi4xi1zhi1fu4bei4shu4': string;
    'pZhang3qi1zhai4wu4yu3ying2yun4zi1jin1bi3lu4': string;
    'pGu3dong1quan2yi4bi3lu4': string;
    'pZhang3qi1fu4zhai4bi3lu4': string;
    'pGu3dong1quan2yi4yu3gu4ding4zi1chan3bi3lu4': string;
    'pFu4zhai4yu3suo3you3zhe3quan2yi4bi3lu4': string;
    'pZhang3qi1zi1chan3yu3zhang3qi1zi1jin1bi3lu4': string;
    'pZi1ben3hua4bi3lu4': string;
    'pGu4ding4zi1chan3jing4zhi2lu4': string;
    'pZi1ben3gu4ding4hua4bi3lu4': string;
    'pChan3quan2bi3lu4': string;
    'pQing1suan4jia4zhi2bi3lu4': string;
    'pGu4ding4zi1chan3bi3zhong4': string;
    'pZi1chan3fu4zhai4lu4': string;
    'pZong3zi1chan3yuan2': string;
    'pJing1ying2xian4jin1jing4liu2liang4dui4xiao1shou4shou1ru4bi3lu4': string;
    'pZi1chan3de5jing1ying2xian4jin1liu2liang4hui2bao4lu4': string;
    'pJing1ying2xian4jin1jing4liu2liang4yu3jing4li4run4de5bi3lu4': string;
    'pJing1ying2xian4jin1jing4liu2liang4dui4fu4zhai4bi3lu4': string;
    'pXian4jin1liu2liang4bi3lu4': string;
    'pDuan3qi1gu3piao4tou2zi1yuan2': string;
    'pDuan3qi1zhai4quan4tou2zi1yuan2': string;
    'pDuan3qi1qi2ta1jing1ying2xing4tou2zi1yuan2': string;
    'pZhang3qi1gu3piao4tou2zi1yuan2': string;
    'pZhang3qi1zhai4quan4tou2zi1yuan2': string;
    'pZhang3qi1qi2ta1jing1ying2xing4tou2zi1yuan2': string;
    'p1nian2yi3nei4ying1shou1zhang4kuan3yuan2': string;
    'p12nian2yi3nei4ying1shou1zhang4kuan3yuan2': string;
    'p23nian2yi3nei4ying1shou1zhang4kuan3yuan2': string;
    'p3nian2yi3nei4ying1shou1zhang4kuan3yuan2': string;
    'p1nian2yi3nei4yu4fu4huo4kuan3yuan2': string;
    'p12nian2yi3nei4yu4fu4huo4kuan3yuan2': string;
    'p23nian2yi3nei4yu4fu4huo4kuan3yuan2': string;
    'p3nian2yi3nei4yu4fu4huo4kuan3yuan2': string;
    'p1nian2yi3nei4qi2ta1ying1shou1kuan3yuan2': string;
    'p12nian2yi3nei4qi2ta1ying1shou1kuan3yuan2': string;
    'p23nian2yi3nei4qi2ta1ying1shou1kuan3yuan2': string;
    'p3nian2yi3nei4qi2ta1ying1shou1kuan3yuan2': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pRi4qi1",
            "baseName": "p_ri4qi1",
            "type": "string",
            "format": ""
        },
        {
            "name": "pTan1bo2mei3gu3shou1yi4yuan2",
            "baseName": "p_tan1bo2mei3gu3shou1yi4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJia1quan2mei3gu3shou1yi4yuan2",
            "baseName": "p_jia1quan2mei3gu3shou1yi4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3shou1yi4diao4zheng3hou4yuan2",
            "baseName": "p_mei3gu3shou1yi4diao4zheng3hou4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pKou4chu2fei1jing1chang2xing4sun3yi4hou4de5mei3gu3shou1yi4yuan2",
            "baseName": "p_kou4chu2fei1jing1chang2xing4sun3yi4hou4de5mei3gu3shou1yi4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3jing4zi1chan3diao4zheng3qian2yuan2",
            "baseName": "p_mei3gu3jing4zi1chan3diao4zheng3qian2yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3jing4zi1chan3diao4zheng3hou4yuan2",
            "baseName": "p_mei3gu3jing4zi1chan3diao4zheng3hou4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3jing1ying2xing4xian4jin1liu2yuan2",
            "baseName": "p_mei3gu3jing1ying2xing4xian4jin1liu2yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3zi1ben3gong1ji1jin1yuan2",
            "baseName": "p_mei3gu3zi1ben3gong1ji1jin1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pMei3gu3wei4fen1pei4li4run4yuan2",
            "baseName": "p_mei3gu3wei4fen1pei4li4run4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pDiao4zheng3hou4de5mei3gu3jing4zi1chan3yuan2",
            "baseName": "p_diao4zheng3hou4de5mei3gu3jing4zi1chan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3li4run4lu4",
            "baseName": "p_zong3zi1chan3li4run4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhu3ying2ye4wu4li4run4lu4",
            "baseName": "p_zhu3ying2ye4wu4li4run4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3jing4li4run4lu4",
            "baseName": "p_zong3zi1chan3jing4li4run4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pCheng2ben3fei4yong4li4run4lu4",
            "baseName": "p_cheng2ben3fei4yong4li4run4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pYing2ye4li4run4lu4",
            "baseName": "p_ying2ye4li4run4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhu3ying2ye4wu4cheng2ben3lu4",
            "baseName": "p_zhu3ying2ye4wu4cheng2ben3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pXiao1shou4jing4li4lu4",
            "baseName": "p_xiao1shou4jing4li4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu3ben3bao4chou2lu4",
            "baseName": "p_gu3ben3bao4chou2lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing4zi1chan3bao4chou2lu4",
            "baseName": "p_jing4zi1chan3bao4chou2lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZi1chan3bao4chou2lu4",
            "baseName": "p_zi1chan3bao4chou2lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pXiao1shou4mao2li4lu4",
            "baseName": "p_xiao1shou4mao2li4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pSan1xiang4fei4yong4bi3zhong4",
            "baseName": "p_san1xiang4fei4yong4bi3zhong4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pFei1zhu3ying2bi3zhong4",
            "baseName": "p_fei1zhu3ying2bi3zhong4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhu3ying2li4run4bi3zhong4",
            "baseName": "p_zhu3ying2li4run4bi3zhong4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu3xi1fa1fang4lu4",
            "baseName": "p_gu3xi1fa1fang4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pTou2zi1shou1yi4lu4",
            "baseName": "p_tou2zi1shou1yi4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhu3ying2ye4wu4li4run4yuan2",
            "baseName": "p_zhu3ying2ye4wu4li4run4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing4zi1chan3shou1yi4lu4",
            "baseName": "p_jing4zi1chan3shou1yi4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJia1quan2jing4zi1chan3shou1yi4lu4",
            "baseName": "p_jia1quan2jing4zi1chan3shou1yi4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pKou4chu2fei1jing1chang2xing4sun3yi4hou4de5jing4li4run4yuan2",
            "baseName": "p_kou4chu2fei1jing1chang2xing4sun3yi4hou4de5jing4li4run4yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhu3ying2ye4wu4shou1ru4zeng1zhang3lu4",
            "baseName": "p_zhu3ying2ye4wu4shou1ru4zeng1zhang3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing4li4run4zeng1zhang3lu4",
            "baseName": "p_jing4li4run4zeng1zhang3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing4zi1chan3zeng1zhang3lu4",
            "baseName": "p_jing4zi1chan3zeng1zhang3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3zeng1zhang3lu4",
            "baseName": "p_zong3zi1chan3zeng1zhang3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pYing1shou1zhang4kuan3zhou1zhuan3lu4ci4",
            "baseName": "p_ying1shou1zhang4kuan3zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pYing1shou1zhang4kuan3zhou1zhuan3tian1shu4tian1",
            "baseName": "p_ying1shou1zhang4kuan3zhou1zhuan3tian1shu4tian1",
            "type": "string",
            "format": ""
        },
        {
            "name": "pCun2huo4zhou1zhuan3tian1shu4tian1",
            "baseName": "p_cun2huo4zhou1zhuan3tian1shu4tian1",
            "type": "string",
            "format": ""
        },
        {
            "name": "pCun2huo4zhou1zhuan3lu4ci4",
            "baseName": "p_cun2huo4zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu4ding4zi1chan3zhou1zhuan3lu4ci4",
            "baseName": "p_gu4ding4zi1chan3zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3zhou1zhuan3lu4ci4",
            "baseName": "p_zong3zi1chan3zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3zhou1zhuan3tian1shu4tian1",
            "baseName": "p_zong3zi1chan3zhou1zhuan3tian1shu4tian1",
            "type": "string",
            "format": ""
        },
        {
            "name": "pLiu2dong4zi1chan3zhou1zhuan3lu4ci4",
            "baseName": "p_liu2dong4zi1chan3zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pLiu2dong4zi1chan3zhou1zhuan3tian1shu4tian1",
            "baseName": "p_liu2dong4zi1chan3zhou1zhuan3tian1shu4tian1",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu3dong1quan2yi4zhou1zhuan3lu4ci4",
            "baseName": "p_gu3dong1quan2yi4zhou1zhuan3lu4ci4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pLiu2dong4bi3lu4",
            "baseName": "p_liu2dong4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pSu4dong4bi3lu4",
            "baseName": "p_su4dong4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pXian4jin1bi3lu4",
            "baseName": "p_xian4jin1bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pLi4xi1zhi1fu4bei4shu4",
            "baseName": "p_li4xi1zhi1fu4bei4shu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1zhai4wu4yu3ying2yun4zi1jin1bi3lu4",
            "baseName": "p_zhang3qi1zhai4wu4yu3ying2yun4zi1jin1bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu3dong1quan2yi4bi3lu4",
            "baseName": "p_gu3dong1quan2yi4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1fu4zhai4bi3lu4",
            "baseName": "p_zhang3qi1fu4zhai4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu3dong1quan2yi4yu3gu4ding4zi1chan3bi3lu4",
            "baseName": "p_gu3dong1quan2yi4yu3gu4ding4zi1chan3bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pFu4zhai4yu3suo3you3zhe3quan2yi4bi3lu4",
            "baseName": "p_fu4zhai4yu3suo3you3zhe3quan2yi4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1zi1chan3yu3zhang3qi1zi1jin1bi3lu4",
            "baseName": "p_zhang3qi1zi1chan3yu3zhang3qi1zi1jin1bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZi1ben3hua4bi3lu4",
            "baseName": "p_zi1ben3hua4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu4ding4zi1chan3jing4zhi2lu4",
            "baseName": "p_gu4ding4zi1chan3jing4zhi2lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZi1ben3gu4ding4hua4bi3lu4",
            "baseName": "p_zi1ben3gu4ding4hua4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pChan3quan2bi3lu4",
            "baseName": "p_chan3quan2bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pQing1suan4jia4zhi2bi3lu4",
            "baseName": "p_qing1suan4jia4zhi2bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pGu4ding4zi1chan3bi3zhong4",
            "baseName": "p_gu4ding4zi1chan3bi3zhong4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZi1chan3fu4zhai4lu4",
            "baseName": "p_zi1chan3fu4zhai4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZong3zi1chan3yuan2",
            "baseName": "p_zong3zi1chan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing1ying2xian4jin1jing4liu2liang4dui4xiao1shou4shou1ru4bi3lu4",
            "baseName": "p_jing1ying2xian4jin1jing4liu2liang4dui4xiao1shou4shou1ru4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZi1chan3de5jing1ying2xian4jin1liu2liang4hui2bao4lu4",
            "baseName": "p_zi1chan3de5jing1ying2xian4jin1liu2liang4hui2bao4lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing1ying2xian4jin1jing4liu2liang4yu3jing4li4run4de5bi3lu4",
            "baseName": "p_jing1ying2xian4jin1jing4liu2liang4yu3jing4li4run4de5bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pJing1ying2xian4jin1jing4liu2liang4dui4fu4zhai4bi3lu4",
            "baseName": "p_jing1ying2xian4jin1jing4liu2liang4dui4fu4zhai4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pXian4jin1liu2liang4bi3lu4",
            "baseName": "p_xian4jin1liu2liang4bi3lu4",
            "type": "string",
            "format": ""
        },
        {
            "name": "pDuan3qi1gu3piao4tou2zi1yuan2",
            "baseName": "p_duan3qi1gu3piao4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pDuan3qi1zhai4quan4tou2zi1yuan2",
            "baseName": "p_duan3qi1zhai4quan4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pDuan3qi1qi2ta1jing1ying2xing4tou2zi1yuan2",
            "baseName": "p_duan3qi1qi2ta1jing1ying2xing4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1gu3piao4tou2zi1yuan2",
            "baseName": "p_zhang3qi1gu3piao4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1zhai4quan4tou2zi1yuan2",
            "baseName": "p_zhang3qi1zhai4quan4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "pZhang3qi1qi2ta1jing1ying2xing4tou2zi1yuan2",
            "baseName": "p_zhang3qi1qi2ta1jing1ying2xing4tou2zi1yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p1nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "baseName": "p_1nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p12nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "baseName": "p_12nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p23nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "baseName": "p_23nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p3nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "baseName": "p_3nian2yi3nei4ying1shou1zhang4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p1nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "baseName": "p_1nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p12nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "baseName": "p_12nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p23nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "baseName": "p_23nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p3nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "baseName": "p_3nian2yi3nei4yu4fu4huo4kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p1nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "baseName": "p_1nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p12nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "baseName": "p_12nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p23nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "baseName": "p_23nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "type": "string",
            "format": ""
        },
        {
            "name": "p3nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "baseName": "p_3nian2yi3nei4qi2ta1ying1shou1kuan3yuan2",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RespstockFinancialAnalysisIndicatorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

