/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StockNote {
    'symbol': string;
    'dateTime'?: number;
    'eventNameOpt'?: string;
    'descriptionOpt'?: string;
    'url'?: string;
    'levelOpt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateTime",
            "baseName": "dateTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "eventNameOpt",
            "baseName": "eventNameOpt",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionOpt",
            "baseName": "descriptionOpt",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "levelOpt",
            "baseName": "levelOpt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StockNote.attributeTypeMap;
    }

    public constructor() {
    }
}

