/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppointmentTime } from '../models/AppointmentTime';
import { ScheduleCard } from '../models/ScheduleCard';
import { HttpFile } from '../http/http';

export class RetGetServiceTime {
    'schedule': ScheduleCard;
    'appointments'?: Array<AppointmentTime>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "ScheduleCard",
            "format": ""
        },
        {
            "name": "appointments",
            "baseName": "appointments",
            "type": "Array<AppointmentTime>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RetGetServiceTime.attributeTypeMap;
    }

    public constructor() {
    }
}

